version: 2
archives:
    - format: zip
      # Add more configuration for the archive
builds:
    - env:
          - CGO_ENABLED=1
      # Add binary name
      binary: dw
      # Add GOOS and GOARCH support
      goos:
          - linux
          - windows
          - darwin
      goarch:
          - amd64
          - arm64
